# Generated by Django 4.1.7 on 2023-04-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyTellerApp', '0002_location_tag_story_like_follower_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(default='profile_picture/blank_profile_picture_PDkAhtk.jpg', upload_to='profile_picture'),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_format',
            field=models.IntegerField(choices=[(1, 'Exact Date'), (2, 'Session'), (3, 'Decade'), (4, 'Year'), (5, 'Month')]),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.FileField(blank=True, upload_to='story_images'),
        ),
    ]
