# Generated by Django 4.1.7 on 2023-04-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyTellerApp', '0003_alter_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(default='profile_picture/blank_profile_picture_PDkAhtk.jpg', upload_to='profile_picture/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.FileField(blank=True, upload_to='story_images/'),
        ),
    ]
