# Generated by Django 4.1.7 on 2023-05-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyTellerApp', '0005_location_lines_location_radius_alter_location_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='location',
        ),
        migrations.AddField(
            model_name='story',
            name='locations',
            field=models.ManyToManyField(to='storyTellerApp.location'),
        ),
    ]
