# Generated by Django 4.1.7 on 2023-05-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyTellerApp', '0007_alter_story_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
    ]
