# Generated by Django 4.1.7 on 2023-05-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyTellerApp', '0010_alter_story_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='session',
            field=models.IntegerField(blank=True, choices=[(1, 'fall'), (2, 'winter'), (3, 'Decade'), (4, 'spring'), (5, 'summer')], null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_format',
            field=models.IntegerField(choices=[(1, 'Exact Date'), (2, 'Session'), (3, 'Decade'), (4, 'Year'), (5, 'Month'), (6, 'Date Range')]),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_range_end',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_range_start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='decade',
            field=models.IntegerField(blank=True, choices=[(1, "2020's"), (2, "2010's"), (3, "2000's"), (4, "1990's"), (5, "1980's"), (6, "1970's"), (7, "1960's"), (8, "1950's")], null=True),
        ),
    ]
