# Generated by Django 4.1.7 on 2023-05-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyTellerApp', '0013_remove_like_post_id_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='story',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='story_id',
            field=models.CharField(default='1d6315a6-99b0-4d53-ba0b-67c85f9502f8', max_length=500),
            preserve_default=False,
        ),
    ]
