# Generated by Django 4.1.7 on 2023-05-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyTellerApp', '0015_story_no_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
