# Generated by Django 4.1.7 on 2023-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyTellerApp', '0016_story_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='liked',
        ),
        migrations.AddField(
            model_name='profile',
            name='likedstories',
            field=models.ManyToManyField(null=True, to='storyTellerApp.story'),
        ),
    ]
