# Generated by Django 4.1.7 on 2023-05-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyTellerApp', '0020_alter_story_date_format_alter_story_decade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_format',
            field=models.IntegerField(blank=True, choices=[(1, 'choose a date type'), (2, 'Exact Date'), (3, 'Session'), (4, 'Decade'), (5, 'Year'), (6, 'Month'), (7, 'Date Range')], null=True),
        ),
    ]
