# Generated by Django 4.1.7 on 2023-05-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyTellerApp', '0021_alter_story_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
