# Generated by Django 4.1.7 on 2023-05-15 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyTellerApp', '0023_alter_story_decade_alter_story_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='storyTellerApp.story'),
        ),
    ]
