# Generated by Django 4.1.7 on 2023-05-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyTellerApp', '0025_remove_comment_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='date_range_end',
            new_name='year_end',
        ),
        migrations.RemoveField(
            model_name='story',
            name='date_range_start',
        ),
        migrations.AddField(
            model_name='story',
            name='date_exact_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='decade_end',
            field=models.CharField(blank=True, choices=[(1, 'choose a decade'), (2, "2020's"), (3, "2010's"), (4, "2000's"), (5, "1990's"), (6, "1980's"), (7, "1970's"), (8, "1960's"), (9, "1950's")], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='month_end',
            field=models.CharField(blank=True, choices=[(1, 'choose a month'), (2, 'January'), (3, 'February'), (4, 'March'), (5, 'April'), (6, 'May'), (7, 'June'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='session_end',
            field=models.CharField(blank=True, choices=[(1, 'choose a session'), (2, 'fall'), (3, 'winter'), (4, 'spring'), (5, 'summer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_format',
            field=models.IntegerField(blank=True, choices=[(1, 'choose a date type'), (2, 'Exact Date'), (3, 'Date Range')], null=True),
        ),
    ]
