# Generated by Django 4.1.7 on 2023-05-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyTellerApp', '0026_rename_date_range_end_story_year_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_exact',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_exact_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
