# Generated by Django 4.1.7 on 2023-05-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyTellerApp', '0028_alter_story_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_format',
            field=models.IntegerField(blank=True, choices=[(1, 'choose a date type'), (2, 'Exact Date'), (3, 'Date Range')], null=True),
        ),
    ]
